canal-admin:
  enabled: true
  env:
    enabled: true
    value:
    - name: spring.datasource.address
      value: '172.16.1.17:3306'
    - name: spring.datasource.database
      value: 'canal_manager'
    - name: spring.datasource.username
      value: 'root'
    - name: spring.datasource.password
      value: 'mic_mq@2019'
    - name: spring.datasource.driver-class-name
      value: 'com.mysql.jdbc.Driver'
    - name: spring.datasource.url
      value: 'jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&  useSSL=false'
    - name: server.port
      value: '8089'
    - name: canal.adminUser
      value: 'admin'
    - name: canal.adminPasswd
      value: '0S1BUQXMMSIN26FFE5YPNHI44PU3QL02'
  image:
    pullPolicy: Always
    repository: registry.cn-hangzhou.aliyuncs.com/mypaas/canal-admin
    tag: latest
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: true
    hosts:
    - canal-admin.mypaas.com.cn
    path:
    - /
    tls:
    - hosts:
      - canal-admin.mypaas.com.cn
      secretName: ""
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 0
      memory: 0Mi
  volume_mount:
    enabled: false
    volumes: []
canal-server:
  enabled: true
  env:
    enabled: false
  image:
    pullPolicy: Always
    repository: registry.cn-hangzhou.aliyuncs.com/mypaas/canal-server
    tag: latest
  ingress:
    enabled: false
  replicaCount: 1
  resources:
    limits:
      cpu: 0.5
      memory: 1024Mi
    requests:
      cpu: 0.2
      memory: 218Mi
  volume_mount:
    enabled: true
    volumes: /home/admin/canal-server/conf/canal.properties
  configurationFiles:
    canal.properties: |
      # register ip
      # ${HOSTNAME} 为podname，canal-server-discovery-svc-stable为svc名称
      # StatefulSet类型pod名称是固定的，k8s集群内pod域名规则为pod_name.svc_name.namespace.svc.cluster.local
      #canal.register.ip = canal-server.default.svc.cluster.local

      # canal admin config
      canal.admin.manager = canal-admin:8089
      canal.admin.port = 11110
      canal.admin.user = admin
      canal.admin.passwd = 471991D55FE532EA0A3EC0528149DAD2A0A35085
      # admin auto register
      canal.admin.register.auto = true
      canal.admin.register.cluster = canal
zookeeper:
  enable: true
