affinity: {}
cmd:
  args: '[]'
  command: '[]'
env:
  enabled: true
  value:
  - name: spring.datasource.address
    value: '172.16.1.17:3306'
  - name: spring.datasource.database
    value: 'canal_manager'
  - name: spring.datasource.username
    value: 'root'
  - name: spring.datasource.password
    value: 'mic_mq@2019'
  - name: spring.datasource.driver-class-name
    value: 'com.mysql.jdbc.Driver'
  - name: spring.datasource.url
    value: 'jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false'
  - name: server.port
    value: '8089'
  - name: canal.adminUser
    value: 'admin'
  - name: canal.adminPasswd
    value: '123456'
hpa:
  enabled: false
image:
  pullPolicy: Always
  repository: registry.cn-hangzhou.aliyuncs.com/mypaas/canal-admin
  tag: latest
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  enabled: true
  path:
  - /
livenessProbe:
  enabled: false
  probe:
    httpGet:
      path: /
      port: ''
nodeSelector: {}
ports:
  enabled: true
  port:
  - containerPort: 8089
    name: http
    protocol: TCP
readinessProbe:
  enabled: false
  probe:
    httpGet:
      path: /
      port: ''
replicaCount: 1
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 0
    memory: 0Mi
service:
  enabled: true
  type: ClusterIP
serviceports:
- name: http
  port: 8089
  protocol: TCP
  targetPort: http
tolerations: []
volume_mount:
  enabled: false
  volumes: []
