apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canal-metrics
  namespace: monitoring
  labels:
    app: canal-server
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    port: metric
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: canal-server
