{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "canal-server.name" . }}
  labels:
    app: {{ template "canal-server.name" . }}
    chart: {{ template "canal-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- with .Values.serviceports }}
{{ toYaml . | indent 4 }}
      {{- end }}
  selector:
    app: {{ template "canal-server.name" . }}
    release: {{ .Release.Name }}
{{- end }}